In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])    # 1D array
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
b = np.array([[1,2,3,4,5,6,7,8,9,10]])  # 2D array
c = np.array([[1,2,3,4,5,6,7,8,9,10]]).T  # 2D array
print(b,c)

[[ 1  2  3  4  5  6  7  8  9 10]] [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [4]:
d = np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])  # 2D array
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [6]:
e = np.array([[[0.6,0.9],[0.3,0.4]],[[0.6,0.9],[0.3,0.4]]])  # 3D array
e

array([[[0.6, 0.9],
        [0.3, 0.4]],

       [[0.6, 0.9],
        [0.3, 0.4]]])

In [7]:
e.shape

(2, 2, 2)